services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/config:/etc/nginx
networks: {}
